### ISSUE TITLE
"could not read Username for 'https://github.com': No such device or address"

### ISSUE THREAD

**Issue by nin-jin** [alex-page/blazing-fast-gh-pages-deploy#5]
Last 3 days I see this errors:

https://github.com/eigenmethod/mol/runs/489451050?check_suite_focus=true#step:3:8

```
Run alex-page/blazing-fast-gh-pages-deploy@v1.1.0
  with:
    repo-token: ***
    site-directory: mol
    deploy-branch: gh-pages
    commit-message: Deployed using Blazing fast GitHub Pages deploy
##[error]❌ Failed to deploy to GitHub pages: mol directory failed to push to gh-pages branch
ProcessError: fatal: could not read Username for 'https://github.com': No such device or address
```

Workflow: https://github.com/eigenmethod/mol/blob/master/.github/workflows/deploy.yml

But it works fine there: https://github.com/hyoo-ru/bench.hyoo.ru/blob/master/.github/workflows/deploy.yml

I don't understand why.

**Comment by alex-page** [comment]
Has something changed with the build script you do to make the website?

**Comment by nin-jin** [comment]
Yes, but I have fixed build scripts and now it completes normally. But I can't deploy app.

**Comment by nin-jin** [comment]
It helps:

```
rm -rf mol/.git
```

Why?

**Comment by alex-page** [comment]
Maybe the folder the site is built to cannot have `.git` initialized. I am still trying to figure out what the problem is..

**Comment by nin-jin** [comment]
May be action tries to add to gh-pages this .git folder?

**Comment by alex-page** [comment]
Let me look into this. It sounds very odd.

**Comment by alex-page** [comment]
Hey @nin-jin I don't have a lot of context into the site you are making and the way the repo is set up. I'll try my best to help.

I think there could be a problem with deploying your entire folder to `gh-pages`. Is there a way to only deploy the website without all the other directories? 

As an example my website https://github.com/alex-page/alex-page builds the site in the `src` directory to the `_site` directory. The action then deploys the build site in the `_site` directory to GitHub Pages.

**Comment by nin-jin** [comment]
I need to deploy entire repo. Removing .git is helpful. Deploy from another dir too, I mean.

**Comment by alex-page** [comment]
In your build process can you copy the entire directory without git and deploy that folder?

The other option is something like this to remove the `.git` directory on deployment:
```
name: Deploy site on master

on:
  push:
    branches:
    - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: remove git directory
      run: rm -r .git
    - name: Deploy site to gh-pages branch
      uses: alex-page/blazing-fast-gh-pages-deploy@master
      with:
        repo-token: ${{ secrets.GH_PAT }}
```
